@startuml Prüfungen planen

' Only greyscale
skinparam monochrome true
' Disable shadows
skinparam shadowing false

|User|
start
:App öffnen;
:Prüfungsplan verwalten;
|MyStudium App|
:existierende Prüfungen anzeigen;    
|User|
label repeat
repeat

while(uneingetragene Prüfungen existieren) is (ja)
    :Prüfung hinzufügen;
    :Datum auswählen;
    :Name eingeben;
    |MyStudium App|
    :Eingaben Zwischenspeichern;
    |User|
endwhile(nein)

repeat

while(Material noch nicht hochgeladen) is (ja)
    :Prüfung auswählen; 
    :Material hochladen;
    |MyStudium App|
    :Material Zwischenspeichern;
    |User|
endwhile(nein)

repeat while (Material fehlt?) is (ja) not (nein)

repeat while (uneingetragene Prüfungen?) is (ja) not (nein)

:fertig clicken;
|MyStudium App|
:Konfiguration speichern;
|User|
stop



@enduml
