@startuml Sequenz Lerneinheit absolvieren

activate UI
UI-> Tagesplan: LoadLerneinheitList()
activate Tagesplan
UI <-- Tagesplan: List:String[]
deactivate Tagesplan



loop weiter Lernen

UI -> Tagesplan: LoadLerneinheit()
activate Tagesplan
Tagesplan ->reader: loadFile()
activate reader
Tagesplan -> Timer: start()
activate Timer
Timer --> Tagesplan:True
deactivate Timer
Tagesplan <-- reader:
deactivate reader
UI <--- Tagesplan: Visible PDF
deactivate Tagesplan
UI -> Reader: closeCurrentFile()
activate Reader

UI <-- Reader: Visible PDF
deactivate Reader
UI -> Timer: stop()
activate Timer
UI <-- Timer: elapsedTime
deactivate Timer
UI -->Testgenerator: evaluateTest()
activate Testgenerator
UI<-- Testgenerator: score:Float
deactivate Testgenerator


alt score > threshhold
UI -> Tagesplan: speichereFortschritt()
activate Tagesplan
UI <-- Tagesplan
deactivate Tagesplan
end

end
UI -> Tagesplan: finishDay()
activate Tagesplan
Tagesplan -> Lernplangenerator: adjustCurrentLernplan()
activate Lernplangenerator
Tagesplan <-- Lernplangenerator
UI <-- Tagesplan
deactivate Tagesplan

deactivate Lernplangenerator
UI -> Lernplan: evaluate()
activate Lernplan
Lernplan --> UI
deactivate Lernplan
UI --> UI: Fortschritt anzeigen




@enduml
