@startuml Sequenz Lerneinheit absolvieren

User-> MyStudium_view: Lerneinheitenliste öffnen
activate MyStudium_view
MyStudium_view-> MyStudium_controller: Laden von allen Lerneinheitsübersichten
activate MyStudium_controller
MyStudium_controller-> MyStudium_model: generierten Lernplan abrufen
activate MyStudium_model
MyStudium_model --> MyStudium_controller: heutigen Lernplan schicken
deactivate MyStudium_model
MyStudium_controller --> MyStudium_view: Lerneinheitsübersicht zurückgeben
deactivate MyStudium_controller
MyStudium_view --> User: Tagesübersicht anzeigen
deactivate MyStudium_view
User -> MyStudium_view: Einheit auswählen
activate MyStudium_view
MyStudium_view -> MyStudium_controller: ausgewählte Einheit abrufen
activate MyStudium_controller
MyStudium_controller -> MyStudium_model: Einheit abrufen und Typ ermitteln
activate MyStudium_model
MyStudium_model --> MyStudium_controller: Einheit mit Typ zurückgeben
deactivate MyStudium_model
MyStudium_controller --> MyStudium_view: zugehörigen Viewer und Einheit zurückgeben
deactivate MyStudium_controller

MyStudium_view -> MyStudium_controller: Success, Timer starten
activate MyStudium_controller
MyStudium_controller --> MyStudium_view:
deactivate MyStudium_controller
MyStudium_view --> User: Lernoberfläche anzeigen
deactivate MyStudium_view
activate User
 ... Aktives Lernen ...
User -> MyStudium_view: Lerneinheit Schließen
deactivate User
    alt Lerneinheit abgebrochen
    activate MyStudium_view
    MyStudium_view -> MyStudium_controller:Fortschritt übermitteln
    activate MyStudium_controller
else Lerneinheit abgeschlossen
    MyStudium_view -> MyStudium_controller:Lerneinheit als abgeschlossen markieren
deactivate MyStudium_view    

end

activate MyStudium_view
activate MyStudium_controller
MyStudium_controller -> MyStudium_controller: Lernplan aktualisieren
activate MyStudium_controller

MyStudium_controller -> MyStudium_model: aktualisierten Lernplan speichern
activate MyStudium_model
MyStudium_model --> MyStudium_controller
deactivate MyStudium_model
MyStudium_controller --> MyStudium_controller
deactivate MyStudium_controller
MyStudium_controller --> MyStudium_view: Fortschritt gespeichert
deactivate MyStudium_controller
MyStudium_view --> User: Lernoberfläche schließen
deactivate MyStudium_view
@enduml
