@startuml Use Case Übersicht
left to right direction
skinparam packageStyle rectangle

actor "Studierende" as Student

package "Lernen & Prüfungsorganisation" {

    usecase "Lern-Einheit absolvieren" as lernen
    usecase "Prüfungen planen" as pruefungstermine_planen
    usecase "Lernfortschritt anzeigen" as lernfortschritt /' nicht relevant als usecase'/
    usecase "Karteikarten verwalten" as karteikarten
    usecase "Lernplan ansehen" as lernplan_ansehen
    usecase "Lernplan generieren" as lernplan_generieren
    usecase "Engpasserkennung" as engpasserkennung
    
}

Student --> lernen
Student --> pruefungstermine_planen
Student --> lernfortschritt
Student --> lernplan_generieren
Student --> karteikarten
Student --> lernplan_ansehen
Student --> engpasserkennung



lernen --> lernplan_generieren : <<include>>

lernplan_generieren --> pruefungstermine_planen : <<include>>


engpasserkennung --> lernplan_generieren : <<include>>

lernplan_ansehen --> lernplan_generieren : <<include>>

lernfortschritt --> lernplan_generieren : <<include>>



/'
Prüfungstermine verwalten: Grundlage der software	
Lernmaterial verwalten: Funktion nicht notwendig	
Lernplan erstellen: Grundlage der software	
Lernfortschritt anzeigen: Nicht notwendig für Kernfuktion	
Tagesplan verwalten: Lernfortschritt eintragen notwendig	
Karteikarten verwalten: nice to have 	
Lernplan zugreifen: abhängigkeit nicht gegeben	
Lernplan generieren: notwendig für Lernfortschritt	
Engpasserkennung und Wiederholungsvorschläge: halt dich an lernplan	
'/

@enduml
