@startuml Use Case Übersicht
left to right direction
skinparam packageStyle rectangle

actor "Studierende" as Student

package "Lernen & Prüfungsplattform" {

    usecase "Lern-Einheit absolvieren" as lernen
    usecase "Prüfungen planen" as pruefungstermine_planen
    usecase "Lernfortschritt evaluieren" as lernfortschritt /' nicht relevant als usecase'/
    usecase "Karteikarten verwalten" as karteikarten
    usecase "Lernplan übersicht erzeugen" as lernplan_ansehen
    usecase "Lernplan generieren" as lernplan_generieren
    usecase "Engpasserkennung" as engpasserkennung /'Verb hinzufügen/rausnehemn'/
    usecase "Lernen" as Aktiv_Lernen    
}

Student --> lernen
Student --> Aktiv_Lernen
Student --> pruefungstermine_planen
Student --> lernfortschritt
Student --> lernplan_generieren
Student --> karteikarten
Student --> lernplan_ansehen
Student --> engpasserkennung

/'precondtion statt include'/
lernen --> lernplan_generieren : <<extends>> 

lernplan_generieren --> pruefungstermine_planen : <<extends>>


engpasserkennung --> lernplan_generieren : <<extends>>

lernplan_ansehen --> lernplan_generieren : <<extends>>

lernfortschritt --> lernplan_generieren : <<extends>>

Aktiv_Lernen --> lernen : <<include>>

lernen --> lernfortschritt: <<include>>



/'
Prüfungstermine verwalten: Grundlage der software	
Lernmaterial verwalten: Funktion nicht notwendig	
Lernplan erstellen: Grundlage der software	
Lernfortschritt anzeigen: Nicht notwendig für Kernfuktion	
Tagesplan verwalten: Lernfortschritt eintragen notwendig	
Karteikarten verwalten: nice to have 	
Lernplan zugreifen: abhängigkeit nicht gegeben	
Lernplan generieren: notwendig für Lernfortschritt	
Engpasserkennung und Wiederholungsvorschläge: halt dich an lernplan	
'/

@enduml
