@startuml Lerneinheit absolvieren

' Only greyscale
skinparam monochrome true
' Disable shadows
skinparam shadowing false

|User|
start
:App öffnen;
|MyStudium App|
:Lerneinheit laden;
|User|
:Lerneinheitenliste öffnen;
repeat
:Lerneinheit auswählen;
|MyStudium App|
fork
:Zeiterfassung starten;
fork again
:Typ der Lerneinheit ermitteln;
switch ()
case ([Folien/andere])
    :pdf Reader öffnen;
case ([Übung])
    :bearbeitbare Datei öffnen;
case ([Karteikarten])
    :Anki interface öffnen;
endswitch
end fork
|User|
/'include usecase lernen'/
:Lernen; 
if(Lerneinheit abbrechen?) then([Einheit fertig])
:Lerneinheit abschließen;
else ([Abbrechen])
label abbruch
endif
/'als usecase hinzufügen Wenn durchgefallen kein fortschritt'/
|MyStudium App|
goto abbruch
:Lerneinheit prüfen;
|User|
:Prüfung absolvieren;
|MyStudium App|
if(Bestanden?) then([ja])
:Fortschritt speichern;
else([nein])
endif


:Zeiterfassung stoppen;

|User|
repeat while (weiter Lernen?) is ([weitere Lerneinheiten machen]) not ([fertig für heute])
|User|
:Lerntag beenden;
|MyStudium App|
:Lernplan generieren/automatisch anpassen;
:Lernfortschritt evaluieren;
|User|
stop



@enduml
