@startuml Prüfungen planen

' Only greyscale
skinparam monochrome true
' Disable shadows
skinparam shadowing false

|User|
start
:App öffnen;
repeat
    :Prüfungsplan verwalten;
    |MyStudium App|
    :existierende Prüfungen anzeigen;
    |User|
    if(Prüfungstermine Editieren? ) then( [Prüfungstermin editeren])
        while(Weitere Termine editieren) is ([editieren])
        :existierenden Prüfungstermin auswählen;
        :Prüfungstermin editeren;
        endwhile([existierende Termine sind Korrekt])

    else ([Neue Prüfung anlegen])

        |User|
        label repeat
        repeat

            while(Neue Prüfung eintragen ?) is ([Prüfung eintragen])
                :Prüfung hinzufügen;
                :Datum auswählen;
                :Name eingeben;
                |MyStudium App|
                :Eingaben Zwischenspeichern;
                |User|
            endwhile([keine neue Prüfung eintragen])

            while(weiteres Material hochladen?) is ([Material Hochladen])
                :bestehende Prüfung auswählen; 
                :Material hochladen;
                |MyStudium App|
                :Material Zwischenspeichern;
                |User|
            endwhile([kein neues Material])

        repeat while (Prüfungstermine und Material komplett?) is ([nein]) not ([ja])

    endif
    |MyStudium App|
    :Konfiguration speichern;
    |User|
repeat  while(Alle Daten Korrekt?) is ([Daten müssen überarbeitet werden]) not ([Daten sind korrekt])  
   

    stop



@enduml
